import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientSideWrapper from '@/components/layout/client-side-wrapper'
import { DirectionProvider } from '@/components/layout/direction-provider'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-screen-sm flex justify-center`}
      >
      <DirectionProvider>
          <ClientSideWrapper>
              {children}
          </ClientSideWrapper>
      </DirectionProvider>
      </body>
    </html>
  );
}
